# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding commands

[command]
	literal = "/effect @e[type=cqrepoured:skeleton] minecraft:instant_damage 1 50"
	triggers = [ "mob-skelington" ]
