# Please refer to the wiki page located at https://github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https://discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding the main config file

[triggers]
	[triggers.universal]
		fade_out = "60"
		persistence = "0"
		trigger_delay = "0"
		song_delay = "0"
		start_delay = "40"
		stop_delay = "0"
		fade_in = "60"
	[[triggers.mob]]
		identifier = "skelington1"
		priority = "100"
		fade_in = "20"
		detection_range = "40"
		resource_name = [ "cqrepoured:skeleton" ]
	[[triggers.mob]]
		identifier = "skelington"
		priority = "99"
		mob_targeting = false
		fade_in = "20"
		detection_range = "40"
		resource_name = [ "cqrepoured:skeleton" ]
[songs]
	[[songs.silent]]
		must_finish = true
		triggers = [ "mob-skelington1" ]
	[[songs.silent]]
		play_once = "2"
		must_finish = true
		triggers = [ "mob-skelington" ]
