[triggers]
	[triggers.dimension]
		identifier = "dementia"
		resource_name = [ "10" ]
		start_delay = "4000"
		trigger_delay = "4000"
		stop_delay = "4000"
		song_delay = "4000"
	[triggers.gamestage]
		priority = "200"
		persistence = "100"
		resource_name = [ "cutscene" ]
		fade_in = "150"
		trigger_delay = "80"
		identifier = "cutscene"
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "0"
		fade_out = "0"
		persistence = "0"
		start_delay = "0"
		trigger_delay = "0"
		song_delay = "0"

[songs]
	[[songs.silent]]
		triggers = [ "gamestage-cutscene" ]
	[[songs.silent]]
		chance = "600"
		play_once = "1"
		triggers = [ "dimension-dementia" ]
	[songs.MB1]
		play_once = "1"
		triggers = [ "dimension-dementia" ]
	[songs.MB2]
		play_once = "1"
		triggers = [ "dimension-dementia" ]
	[songs.MB3]
		play_once = "1"
		triggers = [ "dimension-dementia" ]
	[songs.MB4]
		play_once = "1"
		triggers = [ "dimension-dementia" ]
	[songs.MB5]
		play_once = "1"
		triggers = [ "dimension-dementia" ]
	[songs.intro]
		must_finish = true
		play_once = "2"
		triggers = [ "gamestage-cutscene" ]
