#  Main header!
#  Line 2

[songs]
	[songs.Caverns_Layer_2]
		start_at = ""
		[songs.Caverns_Layer_2.loop]
			to = "5000"
			num_loops = "999999"
			from = "1195000"
		triggers = [ "dimension-deep2" "height-LAYER2" "height-LAYER2_2" ]
	[songs.Caverns_Layer_4]
		triggers = [ "dimension-deep2" "height-LAYER4" "height-LAYER4_4" ]
		[songs.Caverns_Layer_4.loop]
			to = "3000"
			num_loops = "999999"
			from = "1220000"

[triggers]
	[[triggers.dimension]]
		fade_in = "0"
		fade_out = "0"
		identifier = "deep"
		priority = "10"
		resource_name = [ "10" ]
	[[triggers.dimension]]
		fade_in = "60"
		fade_out = "60"
		identifier = "deep2"
		priority = "10"
		resource_name = [ "10" ]
	[[triggers.height]]
		check_for_sky = false
		fade_in = "60"
		fade_out = "60"
		identifier = "LAYER2"
		level = "193"
		priority = "10"
	[[triggers.height]]
		check_above_level = true
		check_for_sky = false
		fade_in = "60"
		fade_out = "60"
		identifier = "LAYER2_2"
		level = "128"
		priority = "10"
	[[triggers.height]]
		check_above_level = true
		check_for_sky = false
		fade_in = "60"
		fade_out = "60"
		identifier = "LAYER4_4"
		level = "0"
		priority = "10"
	[[triggers.height]]
		check_for_sky = false
		fade_in = "60"
		fade_out = "60"
		identifier = "LAYER4"
		level = "65"
		priority = "10"
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "0"
		fade_out = "0"
		persistence = "0"

