#############################################################
#Documentation on the wiki                                  #
#    https://wiki.cq-repoured.net/index.php?title=Main_Page #
#############################################################

spFlask = ebwizardry:small_mana_flask,0,1,2,90
spFlask2 = ebwizardry:medium_mana_flask,0,1,2,70
spFlask3 = ebwizardry:large_mana_flask,0,1,2,50

mujnunch = mujmajnkraftsbettersurvival:itemstonenunchaku,0,1,1,70,true,5,20,false,35
lbLeather = spartanweaponry:longbow_leather,0,1,1,30
cbLeather = spartanweaponry:crossbow_leather,0,1,1,30
dstone = spartanweaponry:dagger_stone,0,1,1,70,true,5,20,false,35
lstone = spartanweaponry:longsword_stone,0,1,1,70,true,5,20,false,35
kstone = spartanweaponry:katana_stone,0,1,1,70,true,5,20,false,35
sstone = spartanweaponry:saber_stone,0,1,1,70,true,5,20,false,35
rstone = spartanweaponry:rapier_stone,0,1,1,70,true,5,20,false,35
gstone = spartanweaponry:greatsword_stone,0,1,1,70,true,5,20,false,35
hstone = spartanweaponry:hammer_stone,0,1,1,70,true,5,20,false,35
wstone = spartanweaponry:warhammer_stone,0,1,1,70,true,5,20,false,35
spstone = spartanweaponry:spear_stone,0,1,1,70,true,5,20,false,35
halbstone = spartanweaponry:halberd_stone,0,1,1,70,true,5,20,false,35
pikestone = spartanweaponry:pike_stone,0,1,1,70,true,5,20,false,35
lancstone = spartanweaponry:lance_stone,0,1,1,70,true,5,20,false,35
lbstone = spartanweaponry:longbow_stone,0,1,1,20
cbstone = spartanweaponry:crossbow_stone,0,1,1,20
thrkstone = spartanweaponry:throwing_knife_stone,0,1,1,70,true,5,20,false,35
thrastone = spartanweaponry:throwing_axe_stone,0,1,1,70,true,5,20,false,35
javstone = spartanweaponry:javelin_stone,0,1,1,70,true,5,20,false,35
boomstone = spartanweaponry:boomerang_stone,0,1,1,70,true,5,20,false,35
battlstone = spartanweaponry:battleaxe_stone,0,1,1,70,true,5,20,false,35
macestone = spartanweaponry:mace_stone,0,1,1,70,true,5,20,false,35
stCaestus = spartanweaponry:caestus_studded,0,1,1,70,true,5,20,false,35
dagger_iron = spartanweaponry:dagger_iron,0,1,1,3
longsword_iron = spartanweaponry:longsword_iron,0,1,1,3
katana_iron = spartanweaponry:katana_iron,0,1,1,3
saber_iron = spartanweaponry:saber_iron,0,1,1,3
rapier_iron = spartanweaponry:rapier_iron,0,1,1,3
greatsword_iron = spartanweaponry:greatsword_iron,0,1,1,3
hammer_iron = spartanweaponry:hammer_iron,0,1,1,3
warhammer_iron = spartanweaponry:warhammer_iron,0,1,1,3
spear_iron = spartanweaponry:spear_iron,0,1,1,3
halberd_iron = spartanweaponry:halberd_iron,0,1,1,3
pike_iron = spartanweaponry:pike_iron,0,1,1,3
lance_iron = spartanweaponry:lance_iron,0,1,1,3
lbiron = spartanweaponry:longbow_iron,0,1,1,3
cbiron = spartanweaponry:crossbow_iron,0,1,1,3
throwing_knife_iron = spartanweaponry:throwing_knife_iron,0,1,1,3
throwing_axe_iron = spartanweaponry:throwing_axe_iron,0,1,1,3
javelin_iron = spartanweaponry:javelin_iron,0,1,1,3
boomerang_iron = spartanweaponry:boomerang_iron,0,1,1,3
battleaxe_iron = spartanweaponry:battleaxe_iron,0,1,1,3
mace_iron = spartanweaponry:mace_iron,0,1,1,3

dSword = minecraft:iron_sword,0,1,1,3
sdSword = useless_sword:ironsoulsandsword,0,1,1,3
fdSword = useless_sword:frozenironsword,0,1,1,3
mSword = useless_sword:magmasword,0,1,1,3
tdSword = useless_sword:thornyironsword,0,1,1,3
tiSword = useless_sword:thornystonesword,0,1,1,4
sSword = mysticalworld:silver_sword,0,1,1,4
pSword = useless_sword:prismarinesword,0,1,1,4
cSword = mysticalworld:copper_sword,0,1,1,70,true,5,20,false,25
gSword = minecraft:golden_sword,0,1,1,50,true,5,20,false,25
iSword = minecraft:stone_sword,0,1,1,70,true,5,20,false,35
qSword = useless_sword:quartzsword,0,1,1,70,true,5,20,false,35
eSword = useless_sword:endstonesword,0,1,1,70,true,5,20,false,35
gSword = useless_sword:glowstonesword,0,1,1,70,true,5,20,false,35
miSword = useless_sword:moltenstonesword,0,1,1,70,true,5,20,false,35
isSword = useless_sword:stoneslimesword,0,1,1,70,true,5,20,false,35
cDagger = mysticalworld:copper_knife,0,1,1,70,true,5,20,false,35
sDagger = mysticalworld:silver_knife,0,1,1,4
iDagger = cqrepoured:dagger_stone,0,1,1,70,true,5,20,false,35
dDagger = cqrepoured:dagger_iron,0,1,1,3
iGreatsword = cqrepoured:great_sword_stone,0,1,1,35,true,5,20,false,20
dGreatsword = cqrepoured:great_sword_iron,0,1,1,2
iSpear = cqrepoured:spear_stone,0,1,1,40,true,5,20,false,20
dSpear = cqrepoured:spear_iron,0,1,1,2
bow = minecraft:bow,0,1,1,30
arrow = minecraft:arrow,0,8,16,40
warrow = spartanweaponry:arrow_wood,0,8,16,50
iarrow = spartanweaponry:arrow_stone,0,8,16,40
darrow = spartanweaponry:arrow_diamond,0,6,8,30
earrow = spartanweaponry:arrow_explosive,0,1,6,20
bolt = spartanweaponry:bolt,0,8,16,40
dbolt = spartanweaponry:bolt_diamond,0,6,8,30
farrow = switchbow:arrowfire,0,1,8,25
frarrow = switchbow:arrowfrost,0,1,8,25
triarrow = switchbow:arrowtriple,0,1,8,25
tArrow = quark:arrow_torch,0,1,4,30