#############################################################
#Documentation on the wiki                                  #
#    https://wiki.cq-repoured.net/index.php?title=Main_Page #
#############################################################
goldBlock = minecraft:gold_block,0,1,4,30
enderPearl = minecraft:ender_pearl,0,3,6,20
emerald= minecraft:emerald,0,2,6,50
goldenApple = minecraft:golden_apple,0,1,4,20
notchApple = minecraft:golden_apple,1,1,2,10
dSword = minecraft:iron_sword,0,1,1,15,true,1,4,false
mujnunchi = mujmajnkraftsbettersurvival:itemironnunchaku,0,1,1,15,true,1,4,false
lbiron = spartanweaponry:longbow_iron,0,1,1,15,true,1,4,false
cbiron = spartanweaponry:crossbow_iron,0,1,1,15,true,1,4,false
dagger_iron = spartanweaponry:dagger_iron,0,1,1,15,true,1,4,false
longsword_iron = spartanweaponry:longsword_iron,0,1,1,15,true,1,4,false
katana_iron = spartanweaponry:katana_iron,0,1,1,15,true,1,4,false
saber_iron = spartanweaponry:saber_iron,0,1,1,15,true,1,4,false
rapier_iron = spartanweaponry:rapier_iron,0,1,1,15,true,1,4,false
greatsword_iron = spartanweaponry:greatsword_iron,0,1,1,15,true,1,4,false
hammer_iron = spartanweaponry:hammer_iron,0,1,1,15,true,1,4,false
warhammer_iron = spartanweaponry:warhammer_iron,0,1,1,15,true,1,4,false
spear_iron = spartanweaponry:spear_iron,0,1,1,15,true,1,4,false
halberd_iron = spartanweaponry:halberd_iron,0,1,1,15,true,1,4,false
pike_iron = spartanweaponry:pike_iron,0,1,1,15,true,1,4,false
lance_iron = spartanweaponry:lance_iron,0,1,1,15,true,1,4,false
throwing_knife_iron = spartanweaponry:throwing_knife_iron,0,1,1,15,true,1,4,false
throwing_axe_iron = spartanweaponry:throwing_axe_iron,0,1,1,15,true,1,4,false
javelin_iron = spartanweaponry:javelin_iron,0,1,1,15,true,1,4,false
boomerang_iron = spartanweaponry:boomerang_iron,0,1,1,15,true,1,4,false
battleaxe_iron = spartanweaponry:battleaxe_iron,0,1,1,15,true,1,4,false
mace_iron = spartanweaponry:mace_iron,0,1,1,15,true,1,4,false
bearFist = cqrepoured:spiked_glove,0,1,2,20
tabletlost = tombstone:lost_tablet,0,1,1,80
specSilt = bountifulbaubles:spectralsilt,0,2,6,50
antiqueatlas = antiqueatlas:empty_antique_atlas, 0, 1, 1, 30
burnt = mod_lavacow:burntovipositor,0,1,1,20
spidervenom = cqrepoured:giant_spider_poison,0,1,1,50
glowpowder = xat:glowing_powder,0,2,6,60
recallpotion = bountifulbaubles:potionrecall,0,1,2,25
wormholepotion = bountifulbaubles:potionwormhole,0,1,2,25
pendant = bountifulbaubles:amuletsinempty,0,1,1,25
sunglasses = bountifulbaubles:trinketmagiclenses,0,1,1,22
holyshield = bountifulbaubles:shieldcobalt,0,1,1,22
dreamcatcher = mod_lavacow:dreamcatcher,0,1,1,22
halonecklace = mod_lavacow:halo_necklace,0,1,1,22
crown = bountifulbaubles:crowngold,0,1,1,12
manaCrystal = xat:mana_crystal,0,1,1,20