#Splash screen properties
#Sat Jul 12 21:11:22 BRT 2025
background=598277
memoryGood=0x006000
font=0x7dc8ff
barBackground=0x303030
barBorder=0x00ff11
memoryLow=0x600000
rotate=false
memoryWarn=0xFFFF00
showMemory=true
enabled=true
bar=0x600000
resourcePackPath=resources
logoOffset=0
forgeTexture=fml\:textures/gui/rift.gif
fontTexture=textures/font/ascii.png
